### ISSUE TITLE
Does Hazel support any form of encryption?

### ISSUE THREAD

**Issue by BrixsterPlanet** [willardf/Hazel-Networking#19]
Hey, Forest.

I'm using the Hazel library to develop my MMO video game, and am wondering if it supports any type of high-level encryption. I'm looking for levels of automatic SSL encryption comparable to Secure WebSocket (WSS) or HTTPS. I don't want eavesdroppers to steal my users' credentials, and I do not know if Hazel supports what I'm looking for out of the box.

Is this possible? Thanks

**Comment by edqx** [comment]
As of recently I believe it has DTLS support.

**Comment by willardf** [comment]
Yep, check out the `DtlsConnectionListener` and `DtlsUnityConnection` classes. You can find usage in the `UnitTests/Dtls/ConnectionTests.cs`.
