### ISSUE TITLE
Socket.Poll on listener causing app to freeze during shutdown

### ISSUE THREAD

**Issue by albpb2** [willardf/Hazel-Networking#23]
I'm testing the Hazel library and this `Poll` with an infinite timeout is causing the app (a server with a listener) to freeze in the Unity editor during the listener's dispose on `this.receiveThread.Join()`.

https://github.com/willardf/Hazel-Networking/blob/71ad40411f3f423da44d0c0365c7a50ebf9e0106/Hazel/FewerThreads/ThreadLimitedUdpConnectionListener.cs#L212

**Comment by willardf** [comment]
For the record, this was fixed with 98d9f5d2c8664b19707907d1a7ca4863ec3e396a. Thanks for bringing it up way back when!
