### ISSUE TITLE
Could I attach an audio source to 3d objects(players) with this so people could essentially talk to each other in a virtual space like vrchat?

### ISSUE THREAD

**Issue by thomashaury** [willardf/Hazel-Networking#4]

**Comment by willardf** [comment]
Well, yes and no. 

This library wouldn't *help* you do that very much, but this is a very generic network communication library. If you build up the framework for lobbies, spawning, and moment, then yes, you could attach an audio listener to your game objects and it would work like you expect.

Per the VoIP aspect (the audio source), I wouldn't really suggest you pipe that data through Hazel. Hazel is not secure so you would be leaking players' voice data over the internet and honestly it's too much work to make a good voip implementation. I would find a good plugin instead.

**Comment by thomashaury** [comment]
Okay thanks.
 Regardless, Hazel is still a pretty coo. It's nice having solutions out there that don't steal all your chickens before they can hatch an egg, if ya know what i mean.

**Comment by willardf** [comment]
That's exactly why I started working with it too! Thanks!
